package com.github.yiyan1992.log;

import java.sql.PreparedStatement;
import java.util.Arrays;


public class MySQL5Logger implements MyLogger {

    @Override
    public void debug(String info) {
        printInfo(info);
    }

    @Override
    public void debug(PreparedStatement preparedStatement) {
        printInfo(getAsSqlByPreparedStatement(preparedStatement, getClazzName()));
    }

    @Override
    public void debug(PreparedStatement preparedStatement, String sql) {
        printInfo(getAsSqlByPreparedStatement(preparedStatement, getClazzName()));
        printInfo(sql);
    }

    @Override
    public void debug(PreparedStatement preparedStatement, String sql, int autoGeneratedKeys) {
        printInfo(getAsSqlByPreparedStatement(preparedStatement, getClazzName()));
        printInfo(sql);
        printInfo(autoGeneratedKeys + "");
    }

    @Override
    public void debug(PreparedStatement preparedStatement, String sql, int[] columnIndexes) {
        printInfo(getAsSqlByPreparedStatement(preparedStatement, getClazzName()));
        printInfo(sql);
        printInfo(Arrays.toString(columnIndexes));
    }

    @Override
    public void debug(PreparedStatement preparedStatement, String sql, String[] columnNames) {
        printInfo(getAsSqlByPreparedStatement(preparedStatement, getClazzName()));
        printInfo(sql);
        printInfo(Arrays.toString(columnNames));
    }

    @Override
    public String getClazzName() {
        return "com.mysql.jdbc.PreparedStatement";
    }

}
